fix(Discovery starter kit): Check for metadata before accessing metadata.source.url
watson-developer-cloud/assistant-toolkit pull request #227
Opened 2023-12-06 19:15 UTC by anirudhaBapat

Closes: https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/60518

In the Discovery generic action example, there is a step that directly tries to access metadata.source.url, if metadata is not present which can be the case with discovery document uploads, it prevents it from erroring out.

2023-12-21 15:06 UTC, jwm4 requested changes
Issues with this PR:
1. It only addresses the base WD kit, not the WD->watsonx.ai conversational search kit.  However, the [report that motivated this work item](https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/60518) was about conversational search so presumably about WD->watsonx.ai.  I don't think it is worth fixing this for the base WD kit, because that doesn't get much usage.  I would only do this for the WD->watsonx.ai example in the conversational search directory.
2. Using `${search_result}.metadata` as an expression to check if metadata is present doesn't work -- this check always fails even when the metadata field is present, presumably because it doesn't evaluate to `true` and it appears that WA doesn't treat an object as an implied `true`.
3. Checking if metadata is present is not sufficient.  You also need to check if metadata.url is present.

2024-01-18 18:41 UTC, anirudhaBapat commented
@jwm4 I checked our conversational search starter kit (wd + watsonx) and I see that none of the action steps has a pointer towards url field but only snippet (title & passage text). I guess at some point Mary had removed that from the example. 

<img width="1785" alt="Screenshot 2024-01-18 at 10 37 47 AM" src="https://github.com/watson-developer-cloud/assistant-toolkit/assets/23107360/79b524d5-2540-4af9-931d-2c91e155142b">

So I guess it would just need to be fixed in the base Discovery kit? (I will add another check for metadata.url or metadata.source.url)

2024-03-01 13:56 UTC, jwm4 commented
Sorry this has taken so long!  I checked and Ani is right -- the conversational search starter kit does not have this issue.  I think it would be fine to fix this issue in the base Discovery kit (addressing issues 2 and 3 that I raised).  However, usability improvements to the base Discovery kit are not a priority at this time, so I think it would also be fine to just close this PR without merging.

2024-04-18 18:20 UTC, anirudhaBapat commented
Okay closing.

2024-04-18 18:20 UTC, closed without merging