feat: Support nested query in search integration
watson-developer-cloud/assistant-toolkit pull request #262
Opened 2024-04-15 14:37 UTC by zach-shu

This PR is to add instructions on how to use nested queries in search integration to search over nested documents. It also fixes an issue for the watsonx.ai starter-kit.

Signed up by: zhongzheng.shu@ibm.com

2024-04-15 16:14 UTC, rfazeli requested changes
Thank you Zach, this looks great. I have a few comments below

2024-04-15 16:14 UTC, rfazeli commented on integrations/extensions/docs/elasticsearch-install-and-setup/how_to_index_pdf_and_office_documents_elasticsearch.md
> +            "model_text": "How many points do I earn on hotel vacations in the topaz card"
This should probably be `"model_text":"$QUERY"` as well

2024-04-15 16:14 UTC, rfazeli commented on integrations/extensions/docs/elasticsearch-install-and-setup/README.md
> +#### c. Nested query with ELSER
Nested query is only for pdf/doc search and web crawler right? Do we want to mention that?

2024-04-16 15:06 UTC, zach-shu commented on integrations/extensions/docs/elasticsearch-install-and-setup/README.md
> +#### c. Nested query with ELSER
Good catch, Reza! The nested query is not only for PDFs or web crawlers. I did add the nested query instructions to the PDF ingestion and web crawl guides.

2024-04-16 17:35 UTC, rfazeli commented on integrations/extensions/docs/elasticsearch-install-and-setup/README.md
> +#### c. Nested query with ELSER
Thanks Zach, I think the first comment is not addressed otherwise everything else looks good to me.

2024-04-23 14:24 UTC, rfazeli approved these changes
Thanks for adding the extra notes. All looks good to me.

2024-04-23 17:48 UTC, merged