Zendesk Guide starter kit
watson-developer-cloud/assistant-toolkit pull request #39
Opened 2022-07-31 00:09 UTC by jwm4

Starter kit for article search using Zendesk Guide

2022-08-04 11:10 UTC, amiddavid requested changes

2022-08-04 14:13 UTC, jwm4 commented on integrations/extensions/starter-kits/zendesk-guide/README.md
> +  - Click the fX button to add a variable and add new session variable `query_text` and select "Expression" type and then put `input.text` or `input.original_text` as the expression.  The former will
I haven't been able to reliably reproduce them so I really don't know.  I haven't reported anything because I don't know what I am dealing with.

2022-08-04 14:16 UTC, jwm4 commented on integrations/extensions/starter-kits/zendesk-guide/README.md
> +This is a starter kit for accessing the Zendesk "Search Articles" API, which is part of the Zendesk Guide feature.  It is one of two starter kits we have for working with Zendesk.  The other is the [
Fixed, except the template _requires_ visuals for the last section, so that still needs to be done.

2022-08-04 14:16 UTC, jwm4 commented on integrations/extensions/starter-kits/zendesk-guide/README.md
> +- Go to `Variables > Created by you` and add: query_text, link0, link1, link2, title0, title1, title2, snippet0, snippet1, and snippet2.
Done

2022-08-08 18:29 UTC, sne3091 commented on integrations/extensions/starter-kits/zendesk-guide/zendesk-article-search-openapi.json
> +{
@amiddavid I've incorporated some changes for this, could you please take a look now? 
<img width="1406" alt="Screen Shot 2022-08-08 at 11 29 13 AM" src="https://user-images.githubusercontent.com/6188953/183488080-5222b282-6d43-47e6-bbb0-35b5d3a37f2f.png">

2022-08-08 18:30 UTC, sne3091 commented on integrations/extensions/starter-kits/zendesk-guide/README.md
> +- Create a new action and put "Search" in "What does your customer say to start this interaction?".  Add step 1:
@amiddavid Added the visuals, please take a look

2022-08-09 19:47 UTC, sne3091 commented on integrations/extensions/starter-kits/zendesk-guide/README.md
> +- Follow the steps listed in [Pre-Req: Getting Auth Keys and Configuring Your Server](https://github.com/watson-developer-cloud/assistant-toolkit/tree/master/integrations/extensions/starter-kits/zend
This step is already listed in the `Pre-Requisite Steps` section, so it seems redundant

2022-08-10 12:09 UTC, amiddavid commented on integrations/extensions/starter-kits/zendesk-guide/README.md
> +  - Click the fX button to add a variable and add new session variable `query_text` and select "Expression" type and then put `input.text` or `input.original_text` as the expression.  The former will
my suggestion is to remove it from the official doc

2022-08-10 12:21 UTC, amiddavid approved these changes
There is a comment by @sne3091 that should be addressed

2022-08-15 19:16 UTC, sne3091 commented on integrations/extensions/starter-kits/zendesk-guide/README.md
> +  - Click the fX button to add a variable and add new session variable `query_text` and select "Expression" type and then put `input.text` or `input.original_text` as the expression.  The former will
@jwm4 Could you please check the update that I made here based on David's suggestion. If it looks good then we're good to merge this PR

2022-08-16 12:33 UTC, jwm4 commented on integrations/extensions/starter-kits/zendesk-guide/README.md
> +  - Click the fX button to add a variable and add new session variable `query_text` and select "Expression" type and then put `input.text` or `input.original_text` as the expression.  The former will
Hi.  Your updated text looks good to me for now, and I think we should merge as-is.   Eventually though, I think we should also spend more time working with `input.original_text` to see if we can identify a reproducible bug that we can report and get prioritized.

2022-08-18 16:35 UTC, jwm4 commented
Converted PR back to draft because Collin and Arnesh are still working on getting final approval to release.

2022-10-03 19:05 UTC, jwm4 commented
Closing this PR because it is superseded by https://github.com/watson-developer-cloud/assistant-toolkit/pull/47 which is now merged

2022-10-03 19:05 UTC, closed without merging